name = "Faroese"
version = "0.1.2"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fo"

[windows]
system_product_code = "{69400DEA-DB07-4923-A027-189C3C543DBA}_is1"
legacy_product_codes = [
    { value = "9392946B-9D11-4383-8705-6CCD61C1CEE7", kind = "nsis" },
    { value = "1A1794E3-5B2F-487E-AA1C-34FF191F6BEB", kind = "nsis" },
    { value = "{2B7F7DEF-5FFC-4ACE-B706-FC6DD1DDC070}", kind = "msi" }
]
extra_locales = { fo-FO = "fo" }
