name = "Faroese"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fo"

[windows]
system_product_code = "1A1794E3-5B2F-487E-AA1C-34FF191F6BEB"
msoffice_product_code = "9392946B-9D11-4383-8705-6CCD61C1CEE7"
