#!/bin/bash

# Automake interprets the exit status as follows:
# - an exit status of 0 will denote a success
# - an exit status of 77 a skipped test
# - an exit status of 99 a hard error
# - any other exit status will denote a failure.


# Test that all noun lemmas do generate as themselves:

# 1. Extract the lemmas, adding noun-specific strings to exclude:
$GTCORE/scripts/extract-lemmas.sh \
	${srcdir}/../../src/morphology/stems/noun.lexc \
	"(CmpN/Last)" \
	> nouns.txt

# 2. Run the lemmas through the generator(s), and count the misses:
# Test both Xerox and Hfst transducers if available:
for f in  .xfst .hfst; do
	if [ $f == ".xfst" ]; then
		lookuptool="lookup -q -flags mbTT"
	else
		lookuptool="hfst-lookup -q"
	fi
	if [ -f "${srcdir}/../../src/generator.gt$f" ]; then
		sed 's/$/+N+Msc+Sg+Nom+Indef/' nouns.txt | \
				$lookuptool ${srcdir}/../../src/generator.gt$f \
				> gen-nouns$f.txt
		if [ `grep '\?' gen-nouns$f.txt | wc -l` -gt 0 ]; then
			echo Some lemmas in ${srcdir}/../../src/morphology/stems/noun.lexc
			echo can NOT be generated by the corresponding generator.
			echo See gen-nouns$f.txt for the problem lemmas.
			exit 1
		else
			rm -f gen-nouns$f.txt
		fi
	fi
done
rm -f nouns.txt
