template = "https://github.com/giellalt/template-lang-und"
rev_id = 298
template_sha = "4822abccfb9b3ce82bf2876217cde02b5f647d14"

[replacements]
__GLOTTOLOG_ID__ = "faro1244"
__REPO__ = "lang-fao"
__UND2C__ = "fo"
__UNDEFINED__ = "Faroese"
__UND__ = "fao"
