template = "https://github.com/giellalt/template-lang-und"
rev_id = 346
template_sha = "f98c2a37b9866895a157f22bea282f596e7a321a"

[replacements]
__GLOTTOLOG_ID__ = "faro1244"
__REPO__ = "lang-fao"
__UND2C__ = "fo"
__UNDEFINED__ = "Faroese"
__UND__ = "fao"
