template = "https://github.com/giellalt/template-lang-und"
rev_id = 300
template_sha = "0371712ab0950051a69847be792b3ad6c2a463ac"

[replacements]
__GLOTTOLOG_ID__ = "faro1244"
__REPO__ = "lang-fao"
__UND2C__ = "fo"
__UNDEFINED__ = "Faroese"
__UND__ = "fao"
