remote_theme: giellalt/jekyll-theme-giellalt@main
title: Faroese NLP Grammar
description: Finite state and Constraint Grammar based analysers, proofing tools and other resources
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
