---
name: Docs
on:
  push:
    branches:
      - 'main'

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v6
        with:
          path: lang

      - name: Install minimal dependencies
        run: sudo apt-get update && sudo apt-get install -y gawk bc autoconf

      - name: Build giella-core
        env:
          TERM: dumb
        run: cd giella-core && ./autogen.sh && ./configure --disable-configure-errors && make

      - name: Generate docs
        env:
          TERM: dumb
        run: |
          cd lang
          ./autogen.sh
          mkdir -p build && cd build
          ../configure --without-hfst --without-foma --disable-configure-errors
          make -C docs

      # Mermaid processing starts here:
      - name: get list of files
        id: getfile
        run: |
          echo "files=$(find lang/docs -name '*.md' | xargs)" >> $GITHUB_OUTPUT

      - name: print list of files for debugging
        run: |
          echo ${{ steps.getfile.outputs.files }}

      # The actual Mermaid compilation
      - name: compile mermaid
        uses: divvun/compile-mermaid-markdown-action@main
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'lang/docs/mermaid-svgs'
        env:
          HIDE_CODEBLOCKS: 1
          # The next one must be declared, with an empty value, for paths to work for us:
          ABSOLUTE_IMAGE_LINKS:
          OUTPUT_FILE_TYPE: "svg"

      - name: list generated svg files
        run: |
          cd lang && ls -l docs/mermaid-svgs
      # Mermaid processing ends here

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: lang/docs/
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v5
