---
name: Docs
on:
  push:
    branches:
      - 'main'
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v6
        with:
          path: lang

      - name: Install minimal dependencies
        run: sudo apt-get update && sudo apt-get install -y gawk bc autoconf

      - name: Build giella-core
        env:
          TERM: dumb
        run: cd giella-core && ./autogen.sh && ./configure --disable-configure-errors && make

      - name: Generate docs
        env:
          TERM: dumb
        run: |
          cd lang
          ./autogen.sh
          mkdir -p build && cd build
          ../configure --without-hfst --without-foma --disable-configure-errors
          make -C docs

      # Mermaid processing starts here:
      - name: get list of files
        id: getfile
        run: |
          echo "files=$(find lang/docs -name '*.md' | xargs)" >> $GITHUB_OUTPUT

      - name: print list of files for debugging
        run: |
          echo ${{ steps.getfile.outputs.files }}

      # The actual Mermaid compilation
      - name: compile mermaid
        uses: divvun/compile-mermaid-markdown-action@main
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'lang/docs/mermaid-svgs'
        env:
          HIDE_CODEBLOCKS: 1
          # The next one must be declared, with an empty value, for paths to work for us:
          ABSOLUTE_IMAGE_LINKS:
          OUTPUT_FILE_TYPE: "svg"

      - name: list generated svg files
        run: |
          cd lang && ls -l docs/mermaid-svgs
      # Mermaid processing ends here

      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lang/docs/
          enable_jekyll: true
